// spamoor-premine derives spamoor's child wallets from a sim config and
// premines them.
//
//	spamoor-premine -sim sim.yaml                        print the premine block
//	spamoor-premine -sim sim.yaml -inject                rewrite the block in the config
//	spamoor-premine -sim sim.yaml -check genesis.json    assert every wallet is funded
//
// Spamoor funds its child wallets on chain and waits for the funding to
// confirm before the scenario starts. On an EL running --maxpeers 0 that
// transaction only confirms when that one node proposes, which at 100 nodes
// never happened. A child that is already rich at genesis is skipped
// (prepareWallet only funds below --refill-balance), so the scenario starts on
// its first tick.
//
// The child key is spamoor's own (walletpool.go prepareChildWallet):
//
//	childKey = sha256(rootPrivKey || bigEndianUint64(idx) || seed)
//
// The seed has to be pinned with --seed in the instance's extra_args. Spamoor's
// default is "<scenario>-<random int>", so without it the addresses change
// every run.
package main

import (
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"math/big"
	"os"
	"regexp"
	"sort"
	"strings"

	"github.com/ethereum/go-ethereum/crypto"
	"gopkg.in/yaml.v3"
)

const (
	balance = "1000000ETH"
	begin   = "    # BEGIN spamoor child wallets"
	end     = "    # END spamoor child wallets"
)

var seedFlag = regexp.MustCompile(`--seed\s+(\S+)`)

type instance struct {
	name    string
	privkey string
	seed    string
	count   int
}

type simConfig struct {
	Ethereum struct {
		Clients map[string]struct {
			Type       string `yaml:"type"`
			ExtraArgs  string `yaml:"extra_args"`
			MaxWallets int    `yaml:"max_wallets"`
			PrivateKey string `yaml:"private_key"`
		} `yaml:"clients"`
	} `yaml:"ethereum"`
}

func main() {
	sim := flag.String("sim", "", "ethshadow sim config with a spamoor premine block")
	doInject := flag.Bool("inject", false, "rewrite the premine block in the sim config")
	genesis := flag.String("check", "", "EL genesis.json to assert every wallet is funded in")
	flag.Parse()
	if *sim == "" || (*doInject && *genesis != "") {
		flag.Usage()
		os.Exit(2)
	}
	insts, err := instances(*sim)
	if err != nil {
		fatal(err)
	}
	switch {
	case *doInject:
		err = inject(*sim, insts)
	case *genesis != "":
		err = check(*genesis, insts)
	default:
		fmt.Println(block(insts))
	}
	if err != nil {
		fatal(err)
	}
}

func fatal(v any) {
	fmt.Fprintln(os.Stderr, v)
	os.Exit(1)
}

// instances lists every spamoor client of the config, sorted by name.
func instances(path string) ([]instance, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg simConfig
	if err := yaml.Unmarshal(raw, &cfg); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	var out []instance
	for name, c := range cfg.Ethereum.Clients {
		if c.Type != "spamoor" {
			continue
		}
		m := seedFlag.FindStringSubmatch(c.ExtraArgs)
		if m == nil {
			return nil, fmt.Errorf(
				"%s: no --seed in extra_args; child addresses would be random every run", name)
		}
		if c.MaxWallets == 0 {
			return nil, fmt.Errorf(
				"%s: max_wallets must be set, otherwise the scenario picks the count", name)
		}
		out = append(out, instance{name: name, privkey: c.PrivateKey, seed: m[1], count: c.MaxWallets})
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("%s: no spamoor clients", path)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out, nil
}

// wallets returns the root address followed by the child addresses.
func wallets(inst instance) ([]string, error) {
	root, err := crypto.HexToECDSA(strings.TrimPrefix(inst.privkey, "0x"))
	if err != nil {
		return nil, fmt.Errorf("%s: private_key: %w", inst.name, err)
	}
	parent := crypto.FromECDSA(root)
	out := []string{crypto.PubkeyToAddress(root.PublicKey).Hex()}
	for i := 0; i < inst.count; i++ {
		msg := make([]byte, 0, len(parent)+8+len(inst.seed))
		msg = append(msg, parent...)
		msg = binary.BigEndian.AppendUint64(msg, uint64(i))
		msg = append(msg, inst.seed...)
		sum := sha256.Sum256(msg)
		child, err := crypto.HexToECDSA(hex.EncodeToString(sum[:]))
		if err != nil {
			return nil, fmt.Errorf("%s: child %d: %w", inst.name, i, err)
		}
		out = append(out, crypto.PubkeyToAddress(child.PublicKey).Hex())
	}
	return out, nil
}

func block(insts []instance) string {
	lines := []string{
		begin, "    # (generated by spamoor-premine -- do not hand-edit)", "    premine:",
	}
	for _, inst := range insts {
		addrs, err := wallets(inst)
		if err != nil {
			fatal(err)
		}
		lines = append(lines, fmt.Sprintf(
			"      # %s: seed %s, %d child wallets", inst.name, inst.seed, inst.count))
		for _, a := range addrs[1:] {
			lines = append(lines, fmt.Sprintf("      %q: %q", a, balance))
		}
	}
	return strings.Join(append(lines, end), "\n")
}

func inject(path string, insts []instance) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	text := string(raw)
	start := strings.Index(text, begin)
	stop := strings.Index(text, end)
	if start < 0 || stop < 0 {
		return fmt.Errorf("%s: no BEGIN/END spamoor child wallets markers", path)
	}
	text = text[:start] + block(insts) + text[stop+len(end):]
	if err := os.WriteFile(path, []byte(text), 0o644); err != nil {
		return err
	}
	total := 0
	for _, inst := range insts {
		total += inst.count
	}
	fmt.Printf("injected %d child wallets from %d spamoor instances into %s\n",
		total, len(insts), path)
	return nil
}

// check asserts every root and child wallet is in the EL genesis alloc with a
// balance. The root never funds anything once the children are rich, but
// spamoor reads its balance at startup and a zero balance means the wrong
// mnemonic account was used.
func check(genesisPath string, insts []instance) error {
	raw, err := os.ReadFile(genesisPath)
	if err != nil {
		return err
	}
	var genesis struct {
		Alloc map[string]struct {
			Balance string `json:"balance"`
		} `json:"alloc"`
	}
	if err := json.Unmarshal(raw, &genesis); err != nil {
		return fmt.Errorf("%s: %w", genesisPath, err)
	}
	have := map[string]string{}
	for a, v := range genesis.Alloc {
		have[strings.ToLower(a)] = v.Balance
	}
	var bad []string
	checked := 0
	for _, inst := range insts {
		addrs, err := wallets(inst)
		if err != nil {
			return err
		}
		for i, a := range addrs {
			checked++
			kind := "child"
			if i == 0 {
				kind = "root"
			}
			bal, ok := have[strings.ToLower(a)]
			switch {
			case !ok:
				bad = append(bad, fmt.Sprintf("%s %s %s: absent", inst.name, kind, a))
			case isZero(bal):
				bad = append(bad, fmt.Sprintf("%s %s %s: zero balance", inst.name, kind, a))
			}
		}
	}
	if len(bad) > 0 {
		return fmt.Errorf("FAIL: %d spamoor wallets missing from %s\n  %s",
			len(bad), genesisPath, strings.Join(bad, "\n  "))
	}
	fmt.Printf("OK: all %d spamoor wallets (roots + children) of %d instances are in %s\n",
		checked, len(insts), genesisPath)
	return nil
}

func isZero(balance string) bool {
	n, ok := new(big.Int).SetString(balance, 0)
	return !ok || n.Sign() == 0
}
